//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefReview.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/Desktop/savaitės/Ataskaitinė (2).mdb")]
        public string DefectDBPath {
            get {
                return ((string)(this["DefectDBPath"]));
            }
            set {
                this["DefectDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/Documents/Visual Studio 2012/Projects/DefReview/db/Options.accdb")]
        public string OptionsDBPath {
            get {
                return ((string)(this["OptionsDBPath"]));
            }
            set {
                this["OptionsDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documents\\Visual Studio 2012\\Projects\\DefReview\\templates\\KMVsQueryTemplate.xl" +
            "sx")]
        public string KMVsQueryTemplatePath {
            get {
                return ((string)(this["KMVsQueryTemplatePath"]));
            }
            set {
                this["KMVsQueryTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A3")]
        public string KMVsQueryTopLeftCell {
            get {
                return ((string)(this["KMVsQueryTopLeftCell"]));
            }
            set {
                this["KMVsQueryTopLeftCell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("query")]
        public string KMVsQueryWorksheetName {
            get {
                return ((string)(this["KMVsQueryWorksheetName"]));
            }
            set {
                this["KMVsQueryWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} - {1:d}.xlsx")]
        public string KMVsQueryFileNameTemplate {
            get {
                return ((string)(this["KMVsQueryFileNameTemplate"]));
            }
            set {
                this["KMVsQueryFileNameTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/Desktop/output")]
        public string KMVsQueryOutputFolder {
            get {
                return ((string)(this["KMVsQueryOutputFolder"]));
            }
            set {
                this["KMVsQueryOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:d} - {1:d} summary2 errors.txt")]
        public string Summary2ErrorFileNameTemplate {
            get {
                return ((string)(this["Summary2ErrorFileNameTemplate"]));
            }
            set {
                this["Summary2ErrorFileNameTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Desktop\\output")]
        public string SummaryOutputFolder {
            get {
                return ((string)(this["SummaryOutputFolder"]));
            }
            set {
                this["SummaryOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documents\\Visual Studio 2012\\Projects\\DefReview\\templates\\Summary2Template.xls" +
            "x")]
        public string Summary2TemplatePath {
            get {
                return ((string)(this["Summary2TemplatePath"]));
            }
            set {
                this["Summary2TemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Summary2")]
        public string Summary2WorksheetName {
            get {
                return ((string)(this["Summary2WorksheetName"]));
            }
            set {
                this["Summary2WorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:d} - {1:d} summary2.xlsx")]
        public string Summary2OutputFileNameTemplate {
            get {
                return ((string)(this["Summary2OutputFileNameTemplate"]));
            }
            set {
                this["Summary2OutputFileNameTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1")]
        public string Summary2HeaderAddress {
            get {
                return ((string)(this["Summary2HeaderAddress"]));
            }
            set {
                this["Summary2HeaderAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1")]
        public string Summary1HeaderAddress {
            get {
                return ((string)(this["Summary1HeaderAddress"]));
            }
            set {
                this["Summary1HeaderAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:d} - {1:d} summary1.xlsx")]
        public string Summary1OutputFileNameTemplate {
            get {
                return ((string)(this["Summary1OutputFileNameTemplate"]));
            }
            set {
                this["Summary1OutputFileNameTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documents\\Visual Studio 2012\\Projects\\DefReview\\templates\\Summary1TemplateHori" +
            "zontal.xlsx")]
        public string Summary1TemplatePath {
            get {
                return ((string)(this["Summary1TemplatePath"]));
            }
            set {
                this["Summary1TemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Summary1")]
        public string Summary1WorksheetName {
            get {
                return ((string)(this["Summary1WorksheetName"]));
            }
            set {
                this["Summary1WorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:d} - {1:d} summary1 errors.txt")]
        public string Summary1ErrorFileNameTemplate {
            get {
                return ((string)(this["Summary1ErrorFileNameTemplate"]));
            }
            set {
                this["Summary1ErrorFileNameTemplate"] = value;
            }
        }
    }
}
